database:
    url: ${DATABASE_URL}

data_collection:
    interval_minutes: 15

twitter_bot:
    post_interval_hours: 3
    max_tweets_per_days: 24


api_endpoints:
    coingecko: https://api.coingecko.com/api/v3
    coinapi: https://rest.coinapi.io/v1
    xrpl: wss://xrplcluster.com

api_limits:
    coinapi_daily: 100