database:
    url: ${DATABASE_URL}

data_collection:
    interval_minutes: 15

twitter_bot:
    post_interval_hours: 1
    max_tweets_per_days: 24

logging:
    level: INFO
    file: logs/xrp_insight.log

api_endpoints:
    coingecko: https://api.coingecko.com/api/v3
    xrpl: wss://xrplcluster.com

api_limits:
    coinapi_daily: 100