name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/xrp_insight
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      COINAPI_API_KEY: ${{ secrets.COINAPI_API_KEY }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: xrp_insight

    services:
      postgres:
        image: timescale/timescaledb:latest-pg14
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: xrp_insight
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code formatting with Black
      run: |
        pip install black
        black --check src tests scripts
      continue-on-error: true

    - name: Run database initialization
      run: |
        python scripts/init_db.py

    - name: Run tests
      run: |
        python -m pytest tests

    - name: Check for code formatting issues
      if: ${{ steps.black.outcome == 'failure' }}
      run: |
          echo "Error: Code formatting issues detected. Please run 'black src tests scripts' locally and commit the changes."
          exit 1
